name = "chisai"
main = "src/app.tsx"
compatibility_date = "2023-10-12"

[site]
bucket = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "chisai"
database_id = "d702ec9b-49c2-40a0-abef-73aadf52b21e"
